name: Build

on:
  push:
    branches: 
      - master
    paths:
      - FastMM4.pas
      - FastMM4Messages.pas
      - FastMM4Options.inc

  workflow_dispatch:

jobs:
  build_linux:
    runs-on: self-hosted-linux

    steps:
      - uses: actions/checkout@v2

      - name: Compile a simple demo in ObjFPC mode
        run: cd $GITHUB_WORKSPACE/Tests/Simple && fpc -B -MObjFPC -Tlinux -Px86_64 SimpleTest.dpr

      - name: Compile a simple demo in Delphi mode
        run: cd $GITHUB_WORKSPACE/Tests/Simple && fpc -B -Mdelphi -Tlinux -Px86_64 SimpleTest.dpr

      - name: Compile with various defined options
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDEBUG -g SimpleTest.dpr
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDEBUG -g -dFullDebugMode SimpleTest.dpr
          fpc -B -Mdelphi -Tlinux -Px86_64 -dFullDebugMode SimpleTest.dpr
          fpc -B -Mdelphi -Tlinux -Px86_64 -dAlign16Bytes SimpleTest.dpr
          fpc -B -Mdelphi -Tlinux -Px86_64 -dAlign32Bytes SimpleTest.dpr
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseCustomFixedSizeMoveRoutines SimpleTest.dpr
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseCustomVariableSizeMoveRoutines SimpleTest.dpr
          fpc -B -Mdelphi -Tlinux -Px86_64 -dForceSingleThreaded SimpleTest.dpr
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDisablePauseAndSwitchToThread SimpleTest.dpr
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseSmallBlocksLockedCriticalSection SimpleTest.dpr
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseMediumBlocksLockedCriticalSection SimpleTest.dpr
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseLargeBlocksLockedCriticalSection SimpleTest.dpr
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDontUseASMVersion SimpleTest.dpr
          fpc -B -Mdelphi -Tlinux -Px86_64 -dDisableAsmCodeAlign SimpleTest.dpr


  build_windows:
    runs-on: self-hosted-windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Compile a simple demo in Release mode
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & 'C:\Delphi2007\Main\bin\DCC32.EXE' @('-B', '-U../..', '-DRelease', '-$D-', 'SimpleTestNoRelative.dpr')

      - name: Compile a simple demo with Debug and FullDebugMode
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & 'C:\Delphi2007\Main\bin\DCC32.EXE' @('-B', '-U../..', '-DDEBUG', '-DFullDebugMode', 'SimpleTestNoRelative.dpr')

      - name: Compile a simple demo with Debug but not FullDebugMode
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & 'C:\Delphi2007\Main\bin\DCC32.EXE' @('-B', '-U../..', '-DDEBUG', 'SimpleTestNoRelative.dpr')

      - name: Compile a simple demo without Debug but with FullDebugMode
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          & 'C:\Delphi2007\Main\bin\DCC32.EXE' @('-B', '-U../..', '-DFullDebugMode', '-$D-', 'SimpleTestNoRelative.dpr')

      - name: Compile by FreePascal 32-bit with various defined options
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin32 -Pi386 -dDisableAsmCodeAlign SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin32 -Pi386 -dDEBUG -g SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin32 -Pi386 -dDEBUG -g -dFullDebugMode SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin32 -Pi386 -dFullDebugMode SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin32 -Pi386 -dAlign16Bytes SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin32 -Pi386 -dAlign32Bytes SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin32 -Pi386 -dDontUseCustomFixedSizeMoveRoutines SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin32 -Pi386 -dDontUseCustomVariableSizeMoveRoutines SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin32 -Pi386 -dForceSingleThreaded SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin32 -Pi386 -dDisablePauseAndSwitchToThread SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin32 -Pi386 -dDontUseSmallBlocksLockedCriticalSection SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin32 -Pi386 -dDontUseMediumBlocksLockedCriticalSection SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin32 -Pi386 -dDontUseLargeBlocksLockedCriticalSection SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin32 -Pi386 -dDontUseASMVersion SimpleTest.dpr

      - name: Compile by FreePascal 64-bit with various defined options
        run: |
          cd $GITHUB_WORKSPACE/Tests/Simple
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin64 -Px86_64 -dDisableAsmCodeAlign SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin64 -Px86_64 -dDEBUG -g SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin64 -Px86_64 -dDEBUG -g -dFullDebugMode SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin64 -Px86_64 -dFullDebugMode SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin64 -Px86_64 -dAlign16Bytes SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin64 -Px86_64 -dAlign32Bytes SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin64 -Px86_64 -dDontUseCustomFixedSizeMoveRoutines SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin64 -Px86_64 -dDontUseCustomVariableSizeMoveRoutines SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin64 -Px86_64 -dForceSingleThreaded SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin64 -Px86_64 -dDisablePauseAndSwitchToThread SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin64 -Px86_64 -dDontUseSmallBlocksLockedCriticalSection SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin64 -Px86_64 -dDontUseMediumBlocksLockedCriticalSection SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin64 -Px86_64 -dDontUseLargeBlocksLockedCriticalSection SimpleTest.dpr
          & C:\FPC\3.2.2\bin\i386-win32\fpc.exe -B -Mdelphi -Twin64 -Px86_64 -dDontUseASMVersion SimpleTest.dpr

