# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_linux:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Compile a simple demo in ObjFPC mode
        run: cd $GITHUB_WORKSPACE/Tests/Simple && fpc -B -MObjFPC SimpleTest.dpr

      - name: Compile a simple demo in Delphi mode
        run: cd $GITHUB_WORKSPACE/Tests/Simple && fpc -B -Mdelphi SimpleTest.dpr


  build_windows:
    # The type of runner that the job will run on
    runs-on: self-hosted-windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Compile a simple demo 
        run: |
          cd $Env:GITHUB_WORKSPACE/Tests/Simple
          C:\Delphi2007\Main\bin\DCC32.EXE -B -U../.. SimpleTestNoRelative.dpr
